backend = "wal"
color_space = "lch"
palette = "dark16"
check_contrast = true
fallback_generator = "complementary"
threshold = 10

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
#saturation = 35

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }

kitty = { src='wallust-templates/kitty.conf', dst='~/.config/kitty/colors.conf'}
fuzzel = { template = 'wallust-templates/fuzzel.ini', target = '~/.config/fuzzel/colors.ini' }
hypr = { src = 'wallust-templates/hyprland.conf', dst = '~/.config/hypr/colors.conf' }
hyprlock = { src = 'wallust-templates/hyprlock.conf', dst = '~/.config/hypr/hyprlock-input.conf' }
waybar = { src = 'wallust-templates/waybar.css', dst = '~/.config/waybar/colors.css' }
kvantum-kvconfig = { src = 'wallust-templates/kvantum.kvconfig', dst = '~/.config/Kvantum/soggy-wallust/soggy-wallust.kvconfig' }
kvantum-svg = { src = 'wallust-templates/kvantum.svg', dst = '~/.config/Kvantum/soggy-wallust/soggy-wallust.svg' }
soggy-wallust-gtk = { src = 'wallust-templates/soggy-wallust-gtk.py', dst = '~/.config/wallust/templates/soggy-gtk/scripts/wallust.py' }
starship = { src = 'wallust-templates/starship.toml', dst = '~/.config/starship.toml' }
mako = { src = 'wallust-templates/mako', dst = '~/.config/mako/config' }
